### ISSUE TITLE
What OS

### ISSUE THREAD

**Issue by zghwi** [RaidTheWeb/raidtheweb.pkg.repo#1]
What's your OS
and what language it is written in

**Comment by RaidTheWeb** [comment]
two things to say.
1. issues are for issues with my code.
2. its CobraOS https://github.com/cobrasys/cobraos and its written on top of the javascript VM so it can run in the browser.

**Comment by zghwi** [comment]
1. ok, then add a Q&A section.
2. that's awesome, I like the shell.

**Comment by RaidTheWeb** [comment]
thanks :D care to elaborate on what you mean by Q&A section and where it would go?

Fun Fact: if you create a repo like this and link the raw.githubusercontent.com link to the packagelist.json and type:
`sudo pkg addsource <yourpackagelist.jsonlink>` it will allow you to install custom packages via your repository :)

**Comment by RaidTheWeb** [comment]
my link for the package list would be https://raw.githubusercontent.com/RaidTheWeb/raidtheweb.pkg.repo/main/packagelist.json

if your wondering the sudo password is `tux` as that is my current default.
`sudo pkg addsource https://raw.githubusercontent.com/RaidTheWeb/raidtheweb.pkg.repo/main/packagelist.json`
you could also `sudo su root` then add the source that way, then you can `sudo pkg install <packagename>`

**Comment by zghwi** [comment]
ok
